# Generated by Django 5.1.dev20240112204018 on 2024-01-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_order_payment'),
    ]

    operations = [
    ]
