# Generated by Django 5.1.dev20240112204018 on 2024-01-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20240115_2358'),
    ]

    operations = [
    ]
