# Generated by Django 5.1.dev20240112204018 on 2024-01-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_auto_20240116_0001'),
    ]

    operations = [
    ]
