# Generated by Django 5.0.1 on 2024-01-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20240116_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='gun',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gun',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
